print("Hello World!")
print("Your name")
name = input("Name: ")
print(f"Hello, {name}!")

print("Your Country")
country = input("Country: ")
print("You are from: " + country)

print("Your number")
n = int(input("Enter a number: "))
if n > 0:
    print("Your number is positive.")
elif n < 0:
    print("Your number is negative.")
else:
    print("Your number is zero.")

print("Names")
names = ["Vladimir", "Maiia", "Taisiia", "Tatiana"]
print("The first name is: " + names[0])
print("The second name is: " + names[1])
print("The third name is: " + names[2])
print("The fourth name is: " + names[3])

print("The alphabet")
alphabet = "abcdefghijklmnopqrstuvwxyz"
print("The first letter is: " + alphabet[0])
print("The second letter is: " + alphabet[1])
print("The third letter is: " + alphabet[2])
print("The fourth letter is: " + alphabet[3])
print("The fifth letter is: " + alphabet[4])
print("The sixth letter is: " + alphabet[5])
print("The seventh letter is: " + alphabet[6])
print("The eighth letter is: " + alphabet[7])
print("The ninth letter is: " + alphabet[8])
print("The tenth letter is: " + alphabet[9])
print("The eleventh letter is: " + alphabet[10])
print("The twelfth letter is: " + alphabet[11])
print("The thirteenth letter is: " + alphabet[12])
print("The fourteenth letter is: " + alphabet[13])
print("The fifteenth letter is: " + alphabet[14])
print("The sixteenth letter is: " + alphabet[15])
print("The seventeenth letter is: " + alphabet[16])
print("The eighteenth letter is: " + alphabet[17])
print("The nineteenth letter is: " + alphabet[18])
print("The twentieth letter is: " + alphabet[19])
print("The twenty-first letter is: " + alphabet[20])
print("The twenty-second letter is: " + alphabet[21])
print("The twenty-third letter is: " + alphabet[22])
print("The twenty-fourth letter is: " + alphabet[23])
print("The twenty-fifth letter is: " + alphabet[24])
print("The twenty-sixth letter is: " + alphabet[25])

print("Coordinates")
coordinates = (10, 20)
print("The first coordinate is: " + str(coordinates[0]))
print("The second coordinate is: " + str(coordinates[1]))

print("Names appended and sorted in alphabetical order")
names.append("Masha")
names.sort()
print(names)